{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt"
    acme.cert-manager.io/http01-edit-in-place: "true"
  namespace: ingress
spec:
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
      secretName: "{{ .Release.Name }}-tlss"
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - pathType: "Prefix"
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.port }}
{{ end }}