apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Release.Name }}
    release: kube-prometheus-stack
  name: {{ .Release.Name }}
  namespace: ingress
spec:
  endpoints:
    - port: http-web
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: {{ .Release.Name }}
